# Generated by Django 3.2.13 on 2022-06-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified_at')),
                ('name', models.CharField(editable=False, help_text='Nombre del curso, ejemplo: Python profesional', max_length=50)),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('category', models.CharField(help_text='Categoría del curso, ejemplo: Backend', max_length=30)),
                ('sub_category', models.CharField(help_text='sub Categoría del curso, ejemplo: Python', max_length=30)),
                ('plataform', models.CharField(blank=True, help_text='nombre de la plataforma, ejemplo: platzi', max_length=50, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='course/', verbose_name='profile picture')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='users/certificate/', verbose_name='Resume users')),
                ('leve', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado')], help_text='Dificultad del curso')),
                ('date_approved', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified_at')),
                ('name', models.CharField(help_text='Nombre del lenguaje de programación, ejemplo: Python ', max_length=50)),
                ('category', models.CharField(help_text='category, ejemplo: Backend, Ingles, Froned', max_length=30)),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('sub_category', models.CharField(help_text='sub Categoría del item, ejemplo: Django', max_length=30)),
                ('description', models.TextField(blank=True, help_text='nombre de la plataforma, ejemplo: platzi', max_length=200)),
                ('leve', models.PositiveSmallIntegerField(choices=[(1, 'Básico'), (2, 'Intermedio'), (3, 'Avanzado')], help_text='Dificultad del curso')),
                ('experience', models.DurationField(blank=True, help_text='Experience of items', null=True)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified_at')),
                ('constancy', models.FileField(blank=True, null=True, upload_to='users/work/', verbose_name='constancy work')),
                ('capture', models.ImageField(blank=True, null=True, upload_to='users/work/img/', verbose_name='Capture work constance')),
                ('name', models.CharField(help_text='Nombre de la empresa donde se trabajó, ejemplo: Platzi', max_length=50)),
                ('slug_name', models.SlugField(max_length=40, unique=True)),
                ('rif', models.CharField(blank=True, help_text='Identificación de la empresa', max_length=30)),
                ('position', models.CharField(help_text='Identificación de la empresa', max_length=30)),
                ('description', models.TextField(blank=True, help_text='nombre de la plataforma, ejemplo: platzi', max_length=200)),
                ('link', models.URLField(max_length=150)),
                ('date_init', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('tags', models.ManyToManyField(to='experience.Items')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
