# Generated by Django 3.2.13 on 2022-06-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='category',
            new_name='category_items',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='sub_category',
            new_name='sub_category_items',
        ),
    ]
