# Generated by Django 3.2.13 on 2022-06-06 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0002_auto_20220606_0510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='category_items',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='sub_category_items',
            new_name='sub_category',
        ),
    ]
