# Generated by Django 3.2.13 on 2022-06-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0003_auto_20220606_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(editable=False, help_text='Nombre del curso, ejemplo: Python profesional', max_length=50),
        ),
    ]
