# Generated by Django 3.2.13 on 2022-06-07 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0004_alter_courses_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='date_experience',
        ),
        migrations.AddField(
            model_name='items',
            name='experience',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
