# Generated by Django 3.2.13 on 2022-06-07 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0006_auto_20220607_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='experience',
            field=models.DurationField(blank=True, help_text='Experience of items', null=True),
        ),
    ]
