# Generated by Django 3.2.13 on 2022-06-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0007_alter_items_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='capture',
            field=models.ImageField(blank=True, null=True, upload_to='users/work/img/', verbose_name='Capture work constance'),
        ),
        migrations.AlterField(
            model_name='works',
            name='rif',
            field=models.CharField(blank=True, help_text='Identificación de la empresa', max_length=30),
        ),
    ]
