# Generated by Django 3.2.13 on 2022-06-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was modified', verbose_name='modified_at')),
                ('type_network', models.CharField(choices=[(1, 'Facebook'), (2, 'Instagram'), (3, 'LinkedIn'), (4, 'Twitter'), (5, 'WhatsApp'), (6, 'YouTube')], max_length=20)),
                ('link', models.URLField(max_length=250)),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
