# Generated by Django 3.2.13 on 2022-06-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_verify',
            field=models.BooleanField(default=False, verbose_name='verify users'),
        ),
    ]
