# Generated by Django 3.2.13 on 2022-06-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_is_verify_users_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_experience',
            field=models.DateTimeField(null=True),
        ),
    ]
