# Generated by Django 3.2.13 on 2022-06-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialnetworks', '0001_initial'),
        ('experience', '0003_auto_20220606_1736'),
        ('users', '0005_auto_20220606_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='experience.Courses'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='items',
            field=models.ManyToManyField(related_name='items', to='experience.Items'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='social_networks',
            field=models.ManyToManyField(related_name='social_networks', to='socialnetworks.SocialNetworks'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='works',
            field=models.ManyToManyField(related_name='works', to='experience.Works'),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=models.CharField(choices=[('AF', 'Afganistán'), ('AL', 'Albania'), ('DZ', 'Argelia'), ('AS', 'Samoa Americana'), ('AD', 'Andorra'), ('AO', 'Angola'), ('AI', 'Anguilla'), ('AQ', 'Antártida'), ('AG', 'Antigua y Barbuda'), ('AR', 'Argentina'), ('AM', 'Armenia'), ('AW', 'Aruba'), ('AU', 'Australia'), ('AT', 'Austria'), ('AZ', 'Azerbaiyán'), ('BS', 'Bahamas'), ('BH', 'Baréin'), ('BD', 'Banglades'), ('BB', 'Barbados'), ('BY', 'Bielorrusia'), ('BE', 'Bélgica'), ('BZ', 'Belice'), ('BJ', 'Benin'), ('BM', 'Bermudas'), ('BT', 'Butan'), ('BO', 'Bolivia'), ('BA', 'Bosnia-Herzegovina'), ('BW', 'Botsuana'), ('BR', 'Brasil'), ('IO', 'Territorio Británico del Océano Índico'), ('BN', 'Brunei'), ('BG', 'Bulgaria'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('KH', 'Camboya'), ('CM', 'Camerún'), ('CA', 'Canadá'), ('CV', 'Cabo Verde'), ('KY', 'Islas Caimán'), ('CF', 'República Centroafricana'), ('TD', 'Chad'), ('CL', 'Chile'), ('CN', 'China'), ('CX', 'Isla de Navidad'), ('CC', 'Islas Cocos'), ('CO', 'Colombia'), ('KM', 'Comoras'), ('CG', 'Congo'), ('CD', 'República Democrática del Congo'), ('CK', 'Islas Cook'), ('CR', 'Costa Rica'), ('CI', 'Costa de Marfil'), ('HR', 'Croacia'), ('CU', 'Cuba'), ('CY', 'Chipre'), ('CZ', 'Chequia'), ('DK', 'Dinamarca'), ('DJ', 'Yibuti'), ('DM', 'Dominica'), ('DO', 'República Dominicana'), ('EC', 'Ecuador'), ('EG', 'Egipto'), ('SV', 'El Salvador'), ('GQ', 'Guinea Ecuatorial'), ('ER', 'Eritrea'), ('EE', 'Estonia'), ('ET', 'Etiopía'), ('FK', 'Islas Malvinas'), ('FO', 'Islas Feroe'), ('FJ', 'Fiyi'), ('FI', 'Finlandia'), ('FR', 'Francia'), ('GF', 'Guayana Francesa'), ('PF', 'Polinesia Francesa'), ('GA', 'Gabón'), ('GM', 'Gambia'), ('GE', 'Georgia'), ('DE', 'Alemania'), ('GH', 'Ghana'), ('GI', 'Gibraltar'), ('GR', 'Grecia'), ('GL', 'Groenlandia'), ('GD', 'Granada'), ('GP', 'Guadalupe'), ('GU', 'Guam'), ('GT', 'Guatemala'), ('GG', 'Guernsey'), ('GN', 'Guinea'), ('GW', 'Guinea-Bisau'), ('GY', 'Guyana'), ('HT', 'Haití'), ('VA', 'Ciudad del Vaticano'), ('HN', 'Honduras'), ('HK', 'Hong Kong'), ('HU', 'Hungría'), ('IS', 'Islandia'), ('IN', 'India'), ('ID', 'Indonesia'), ('IR', 'Irán'), ('IQ', 'Iraq'), ('IE', 'Irlanda'), ('IM', 'Isla de Man'), ('IL', 'Israel'), ('IT', 'Italia'), ('JM', 'Jamaica'), ('JP', 'Japón'), ('JE', 'Jersey'), ('JO', 'Jordania'), ('KZ', 'Kazajistán'), ('KE', 'Kenia'), ('KI', 'Kiribati'), ('KP', 'Corea del Norte'), ('KR', 'Corea del Sur'), ('XK', 'Kosovo'), ('KW', 'Kuwait'), ('KG', 'Kirguistán'), ('LA', 'Laos'), ('LV', 'Letonia'), ('LB', 'Líbano'), ('LS', 'Lesoto'), ('LR', 'Liberia'), ('LY', 'Libia'), ('LI', 'Liechtenstein'), ('LT', 'Lituania'), ('LU', 'Luxemburgo'), ('MO', 'Macao'), ('MK', 'República de Macedonia'), ('MG', 'Madagascar'), ('MW', 'Malaui'), ('MY', 'Malasia'), ('MV', 'Maldivas'), ('ML', 'Malí'), ('MT', 'Malta'), ('MH', 'Islas Marshall'), ('MQ', 'Martinica'), ('MR', 'Mauritania'), ('MU', 'Mauricio'), ('YT', 'Mayotte'), ('MX', 'México'), ('FM', 'Estados Federados de Micronesia'), ('MD', 'Moldavia'), ('MC', 'Monaco'), ('MN', 'Mongolia'), ('ME', 'Montenegro'), ('MS', 'Montserrat'), ('MA', 'Marruecos'), ('MZ', 'Mozambique'), ('MM', 'Birmania'), ('NA', 'Namibia'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NL', 'Holanda'), ('AN', 'Antillas Holandesas'), ('NC', 'Nueva Caledonia'), ('NZ', 'Nueva Zelanda'), ('NI', 'Nicaragua'), ('NE', 'Niger'), ('NG', 'Nigeria'), ('NU', 'Niue'), ('NF', 'IslaNorfolk'), ('MP', 'IslasMarianasdelNorte'), ('NO', 'Noruega'), ('OM', 'Omán'), ('PK', 'Pakistán'), ('PW', 'Palaos'), ('PA', 'Panamá'), ('PG', 'Papúa Nueva Guinea'), ('PY', 'Paraguay'), ('PE', 'Perú'), ('PH', 'Filipinas'), ('PN', 'Islas Pitcairn'), ('PL', 'Polonia'), ('PT', 'Portugal'), ('PR', 'Puerto Rico'), ('QA', 'Qatar'), ('RO', 'Rumania'), ('RU', 'Rusia'), ('RW', 'Ruanda'), ('RE', 'Reunion'), ('BL', 'San Bartolome'), ('SH', 'Santa Elena, Ascensión y Tristán de Acuña'), ('KN', 'San Cristóbal y Nieves'), ('LC', 'Santa Lucía'), ('MF', 'Isla de San Martín'), ('PM', 'San Pedro y Miquelon'), ('VC', 'San Vicente y las Granadinas'), ('WS', 'Samoa'), ('SM', 'San Marino'), ('ST', ' Santo Tomé y Príncipe'), ('SA', 'Arabia Saudita'), ('SN', 'Senegal'), ('RS', 'Serbia'), ('SC', 'Seychelles'), ('SL', 'Sierra Leona'), ('SG', 'Singapur'), ('SK', 'Eslovaquia'), ('SI', 'Eslovenia'), ('SB', 'Islas Salomón'), ('SO', 'Somalia'), ('ZA', 'Sudáfrica'), ('SS', 'Sudán del Sur'), ('ES', 'España'), ('LK', 'Sri Lanka'), ('PS', 'Estado de Palestina'), ('SD', 'Sudán'), ('SR', 'Surinam'), ('SJ', 'Svalbard y Jan Mayen'), ('SZ', 'Suazilandia'), ('SE', 'Suecia'), ('CH', 'Suiza'), ('SY', 'Siria'), ('TW', 'Taiwán'), ('TJ', 'Tayikistán'), ('TZ', 'Tanzania'), ('TH', 'Tailandia'), ('TL', 'Timor Oriental'), ('TG', 'Togo'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TT', 'Trinidad y Tobago'), ('TN', 'Túnez'), ('TR', 'Turquía'), ('TM', 'Turkmenistán'), ('TC', 'Islas Turcas y Caicos'), ('TV', 'Tuvalu'), ('UG', 'Uganda'), ('UA', 'Ucrania'), ('AE', 'Emiratos Árabes Unidos'), ('GB', 'Reino Unido'), ('US', 'Estados Unidos'), ('UY', 'Uruguay'), ('UZ', 'Uzbekistán'), ('VU', 'Vanuatu'), ('VE', 'Venezuela'), ('VN', 'Vietnam'), ('VG', 'Islas Vírgenes Británicas'), ('VI', 'Islas Vírgenes de los Estados Unidos'), ('WF', 'Wallis y Futuna'), ('YE', 'Yemen'), ('ZM', 'Zambia'), ('ZW', 'Zimbabue'), ('AX', 'Åland')], default='VE', help_text='Seleccionar país', max_length=2),
        ),
    ]
