# Generated by Django 3.2.13 on 2022-06-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220606_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_experience',
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
